version: '3.5'
services:
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_DATABASE: Space
            MARIADB_USER: ${DBUSER}
            MARIADB_PASSWORD: ${DBPASSWORD}
            MARIADB_RANDOM_ROOT_PASSWORD: '1'
        ports:
            - 3306:3306
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    app:
        image